name: 'Vuepress deploy v2'
description: 'A GitHub Action to build and publish Vuepress sites to GitHub Pages'
author: 'fork from Jenkey2011'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'upload-cloud'
  color: 'gray-dark'
